{% set name = "pymilo" %}
{% set version = "1.2" %}

package:
    name: {{ name|lower }}
    version: {{ version }}
source:
    git_url: https://github.com/openscilab/pymilo
    git_rev: v{{ version }}
build:
    noarch: python
    number: 0
    script: {{ PYTHON }} -m pip install . -vv
requirements:
    host:
        - pip
        - setuptools
        - python >=3.6
    run:
        - python >=3.6
        - numpy >=1.9.0
        - scikit-learn >=0.22.2
        - scipy >=0.19.1
        - requests>=2.0.0
        - uvicorn>=0.14.0
        - fastapi>=0.68.0
        - pydantic>=1.5.0
        - websockets>=9.0

about:
    home: https://github.com/openscilab/pymilo
    license: MIT
    license_family: MIT
    summary: Python library for machine learning input and output
    description: |
        Pymilo is an open source Python package that provides a simple, efficient, and
        safe way for users to export pre-trained machine learning models in a transparent way.
        By this, the exported model can be used in other environments, transferred across different platforms,
        and shared with others. Pymilo allows the users to export the models that are
        trained using popular Python libraries like scikit-learn, and then use them in deployment environments,
        or share them without exposing the underlying code or dependencies.
        The transparency of the exported models ensures reliability and safety for the end users,
        as it eliminates the risks of binary or pickle formats.
        
        Website: https://openscilab.com

        Repo: https://github.com/openscilab/pymilo
extra:
    recipe-maintainers:
        - AHReccese
