name: publish_conda

permissions: read-all

on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
      - '*' # Push events to matching v*, i.e. v1.0, v20.15.10

jobs:
  publish:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4
      - name: publish-to-conda
        uses: sepandhaghighi/conda-package-publish-action@v1.2
        with:
          subDir: 'otherfiles'
          AnacondaToken: ${{ secrets.ANACONDA_TOKEN }}
